// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB3VYIR-uNpat4DWQIcyc_PbugSljZzKM',
    appId: '1:144378392459:web:1e4d69d2a745fda6abc98e',
    messagingSenderId: '144378392459',
    projectId: 'pyme-47f32',
    authDomain: 'pyme-47f32.firebaseapp.com',
    storageBucket: 'pyme-47f32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmDwxpEkiisA_3TOyxk2ovGWN7ksCSevg',
    appId: '1:144378392459:android:18f115d5220ef7b0abc98e',
    messagingSenderId: '144378392459',
    projectId: 'pyme-47f32',
    storageBucket: 'pyme-47f32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOEgWZnpC-bXYpqxIbNrHCKdzC4-1TCZQ',
    appId: '1:144378392459:ios:3ab4d5bd5daa5c89abc98e',
    messagingSenderId: '144378392459',
    projectId: 'pyme-47f32',
    storageBucket: 'pyme-47f32.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOEgWZnpC-bXYpqxIbNrHCKdzC4-1TCZQ',
    appId: '1:144378392459:ios:3ab4d5bd5daa5c89abc98e',
    messagingSenderId: '144378392459',
    projectId: 'pyme-47f32',
    storageBucket: 'pyme-47f32.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB3VYIR-uNpat4DWQIcyc_PbugSljZzKM',
    appId: '1:144378392459:web:de6c8187b25f4cd5abc98e',
    messagingSenderId: '144378392459',
    projectId: 'pyme-47f32',
    authDomain: 'pyme-47f32.firebaseapp.com',
    storageBucket: 'pyme-47f32.firebasestorage.app',
  );
}
